/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package hello.kotlin

import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val classUnderTest = Library()
        assertTrue("Hello, World!" == classUnderTest.sayHello(), ".sayHello() should return 'Hello, World!'")
    }
}
